### ISSUE TITLE
How do I replicate the original Deepsea result using this code?

### ISSUE THREAD

**Issue by datduong** [FunctionLab/selene#131]
Hi, I saw that there is the danQ.py at https://github.com/FunctionLab/selene/blob/master/models/danQ.py. 

I would like to run the danQ.py on the original Deepsea result (in 2015) using this newest code. What do you recommend I should modify in this newest code? What are the command lines to run on this original dataset? 

I see that in the paper says we can edit https://selene.flatironinstitute.org/overview/cli.html#multiple-file-sampler, however, the example only shows the edits for deeper Deepsea. How exactly should I change this file for danQ.py. 

Thanks.

**Comment by kathyxchen** [comment]
Hi @datduong, could you post this in our Google groups? https://groups.google.com/forum/#%21forum/selene-sdk
So that we have a single location where everyone can reference posts about running Selene.

In that post, can you give me some more information on what your use case is? That is, are you trying to do the same exact steps we describe for the "deeper DeepSEA" model but just with the DanQ architecture? Thanks
