### ISSUE TITLE
Type errors with in silico mutagenesis visualization

### ISSUE THREAD

**Issue by rfriedman22** [FunctionLab/selene#174]
There is a type error in `interpret.sequence_logo` when `order == "value"`. The issue occurs regardless of `if np.sum(score_matrix < 0) != 0`, but occurs at the same place -- [here](https://github.com/FunctionLab/selene/blob/39e8d95368e6da13071763b2e2b95b604c9db5e8/selene_sdk/interpret/vis.py#L259-L260) in the True condition and [here](https://github.com/FunctionLab/selene/blob/39e8d95368e6da13071763b2e2b95b604c9db5e8/selene_sdk/interpret/vis.py#L275) in the False condition.

The issue seems to stem from the fact that `sequence_type.BASES_ARR` is a pure Python list, but is getting sliced by an ndarray. Based on the code in the True condition (`sequence_type.BASES_ARR[positive_idx[positive_sort_idx]].flatten()`), it seems like whoever wrote the code expected `sequence_type.BASES_ARR` to be an ndarray.

I'm happy to patch the code, but I'm not sure if converting `BASES_ARR` to an ndarray in the Sequence classes would cause problems in other places. If so, I can patch the code in another way that is local to the `sequence_logo` function.

**Comment by kathyxchen** [comment]
Sorry for the late response @rfriedman22 - hopefully you were able to temporarily patch the code so that you could use the function! Yes, I think `BASES_ARR` used to be an ndarray and we changed it to a list recently... I guess as a workaround we can cast `sequence_type.BASES_ARR` to a numpy array only within the `vis.py` file functions (e.g. instead of `sequence_type.BASES_ARR[positive_idx[positive_sort_idx]].flatten()` used `np.array(sequence_type.BASES_ARR[positive_idx[positive_sort_idx]].flatten()`) - does that seem reasonable?

**Comment by rfriedman22** [comment]
No problem on the late response! Your proposed workaround sounds reasonable to me -- I can patch the code as such as submit a PR.
