### ISSUE TITLE
Question about using model to predict sequences in fasta file

### ISSUE THREAD

**Issue by ymkng** [FunctionLab/selene#83]
Hi,

I trained a model to predict binding of 85 transcription factors. I want to use this model to predict binding on about 3000 unique regions (all 200 bp long). Attached are my training yml , prediction yml and output tsv files. My issue is that the output files looks like it's only looping through the first 64 sequences of my input file. How do I fix this?

thanks,

Michelle 
[MCF7enh_predictions.txt](https://github.com/FunctionLab/selene/files/3278989/MCF7enh_predictions.txt)

[simple_train.txt](https://github.com/FunctionLab/selene/files/3278994/simple_train.txt)

[get_predictions.txt](https://github.com/FunctionLab/selene/files/3278995/get_predictions.txt)

**Comment by ymkng** [comment]
[MCF7enh.txt](https://github.com/FunctionLab/selene/files/3279025/MCF7enh.txt)

(a txt version of my input fasta file) only the first 64 entries are getting looped through in the output (MCF7enh_predictions.txt)

**Comment by evancofer** [comment]
I think this was recently fixed by PR #81 . @kathyxchen is this correct?

**Comment by kathyxchen** [comment]
Yes, it should have been fixed in #81. We have not pushed these changes to the conda release yet, so please let me know if you need help building/installing Selene from `master`. We are hoping to make a new release through bioconda soon, but I haven't decided yet how soon that will be (originally I was aiming for the end of this month)

**Comment by ymkng** [comment]
fixed thanks!!!
