### ISSUE TITLE
Issue when changing sequence length

### ISSUE THREAD

**Issue by ymkng** [FunctionLab/selene#84]
Hi sorry I have another issue,

I want to change the sequence length to 200 and when I do it gives me this issue. 
<img width="875" alt="Screen Shot 2019-06-12 at 11 22 47 AM" src="https://user-images.githubusercontent.com/37229946/59376165-74c58c80-8d04-11e9-81ec-c04910068878.png">

here is the yml file I'm using to train. 

Thanks so much!
[simple_train.txt](https://github.com/FunctionLab/selene/files/3282677/simple_train.txt)

**Comment by kathyxchen** [comment]
I'm inclined to think that this is because the amount of pooling specified in the "deeper deepsea" architecture will reduce to a negative number (see: https://github.com/FunctionLab/selene/blob/master/selene_sdk/utils/example_model.py#L73)

You can try removing some layers/pooling if you want to work with such small sequence lengths

**Comment by ymkng** [comment]
thanks!
