### ISSUE TITLE
question about prediction on sequences score

### ISSUE THREAD

**Issue by ymkng** [FunctionLab/selene#85]
Hi,
I have been reading the documentation and I'm still not sure what the output scores for getting predictions from a trained model means. I noticed that the scores are all from 0-1, is it the probability that a TF will bind to an input region and what is this probability based on?

Another question I have is that if I set my "center_bin_to_predict" to be 200 when training the model, and my "feature_thresholds" is 0.5, do my input TF binding regions have to be at least 200bp long for Selene to classify it as a "binding region"

thanks!

Michelle

**Comment by kathyxchen** [comment]
Hi Michelle,

Yes, you can consider the scores to be 'probabilities'; however, this is a rather loose definition because these values are really just the outputs from the Sigmoid layer (which constrain the values to between 0 and 1 and allow us to make predictions about whether a particular chromatin factor is likely to bind at a region). 

If the threshold is 0.5, the TF binding region needs to cover at least 100bp of the center bin to be classified as a binding region. You can adjust this threshold or the center bin size based on the size of the peaks in your track files. 

Thanks!
Kathy

**Comment by ymkng** [comment]
thanks so much! ...so if my TF binding regions vary in size, between 90-300 base pairs, what would you suggest as the the threshold or center_bin_to_predict to be set to?

**Comment by evancofer** [comment]
I would think `0.45`, or somewhere between `0.40` and `0.50`. I don't have a good sense of how  it will influence performance on your specific data if you set it too small/large, so it might be worth tuning it on some validation data. What do you think @kathyxchen  ?

**Comment by kathyxchen** [comment]
Agree with @evancofer that you can definitely tune this based on validation data. Otherwise you could make the decision by figuring out the distribution of the TF binding region sizes, how they are distributed in the genome, & if you have multiple TFs in your dataset, are there ones at 90bp that you'd be excluding entirely by keeping the threshold this large... etc

**Comment by evancofer** [comment]
@ymkng @kathyxchen  Can this be closed?

**Comment by ymkng** [comment]
thanks!
