### ISSUE TITLE
Getting warning while running Case Study 3

### ISSUE THREAD

**Issue by ashishjain1988** [FunctionLab/selene#91]
I am getting a warning while running the third case study related to the variant effect predictions using the given Alzheimer's dataset.

Warning for one of the SNPs
"UserWarning: For variant (chr4, 178652519, rs6856754, t, c), reference does not match the reference genome. Reference genome contains C instead. Predictions/scores associated with this variant--where we use 't' in the input sequence--will be written to files where the filename is prefixed by 'warning.'"

Due to this, the final figure I am getting is not what is given in the paper. I assume the code is not picking up the predictions which are in the file prefixed with "warning"?

Also, is the variant effect is calculated based on the log2 odd change as mentioned in the DeepSEA paper?

**Comment by kathyxchen** [comment]
Are you using the reference genome FASTA file that we provide in the Zenodo record?

Also, if you are running Selene locally, might be worth it to pull the latest code (we do change the way we handle variant effect prediction warnings, so that all of the predictions are in the same output file and just tagged as `ref_match` True or False). 

Variant effect can be either difference scores or log fold-change, depending on what your use case is. I think for the case study we used difference score.

**Comment by ashishjain1988** [comment]
I am using the same fasta file (male.hg19.fasta) as provided in the Zenodo record. I will try to run it again with the updated code.

**Comment by kathyxchen** [comment]
Can this be closed?

**Comment by kathyxchen** [comment]
You can post follow-ups to this issue/other questions in our newly created google group https://groups.google.com/forum/#!forum/selene-sdk

Thanks!
