### ISSUE TITLE
selene inaccurate predictions

### ISSUE THREAD

**Issue by ymkng** [FunctionLab/selene#98]
I followed the getting started tutorial and trained the GM12878 CTCF binding model. Then I inputted enhancer regions and compared the model's predictions to experimental binding of CTCF in these regions. The model's predictions were vastly different from the experimental CHIP seq binding and I'm wondering why that is?

best,

Michelle

**Comment by kathyxchen** [comment]
I'm not sure what this means. The model is learning patterns in sequences based on the training data. If this training data happens to be measuring peaks/learning sequence patterns different from what you are validating on, that could be why

**Comment by ymkng** [comment]
sorry I'll try to explain again. I'm following the "getting started with selene" example exactly to train the GM12878 CTCF binding model and the performance of the model is exactly the same as shown in the tutorial. With the trained model, I am predicting CTCF binding to regions 200 base pairs long (in a file lets call it fileA).  Then, I run bedtools intersect (with a threshold of 0.5) with CTCF chipseq binding data and regions in fileA. Finally I compared Selene's predicted CTCF binding to regions in fileA to the bedtools intersect binding to regions in fileA and the predictions are very different.

**Comment by kathyxchen** [comment]
It’s entirely possible for this to occur because that example model is only trained on a single track, from a single experiment carried out under a specific set of conditions. You could train a model with more CTCF tracks, separated as different chromatin features, and then see if the averaged prediction was more like what you expect for CTCF binding. It really depends - the model is just learning what is captured in the data, so that’s what it is going to predict.

**Comment by kathyxchen** [comment]
Can this be closed?

**Comment by kathyxchen** [comment]
@ymkng you can post follow-ups to this issue in our newly created google group https://groups.google.com/forum/#!forum/selene-sdk

Thanks!
